### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by bingnanG** [enlighten0707/Body-Part-Map-for-Interactiveness#1]
Thanks for your great works!! :)
I found the visualization of attention results in this paper，could u provide the visualization code？
Thank you for your help.

**Comment by enlighten0707** [comment]
We have uploaded the related code. Please refer to README.md.
Thank you!

**Comment by bingnanG** [comment]
邮件已收到！！

**Comment by bingnanG** [comment]
Thank u very much ！！！
