### ISSUE TITLE
How to generate these files?

### ISSUE THREAD

**Issue by Yuankus** [enlighten0707/Body-Part-Map-for-Interactiveness#10]
I am quite interested in your project. However when i try to train this model on my datasets, i found these files are required. So i wonder if you can tell me how to generate these files below. Thanks a lot if replied! 
![image](https://github.com/enlighten0707/Body-Part-Map-for-Interactiveness/assets/101401466/f3db8d35-4b7d-42d8-9484-83944930b9e0)

**Comment by enlighten0707** [comment]
Hi, :)
1. detr-r50-pre-hico.pth is a pretrained checkpoint provided by [QPIC](https://github.com/hitachi-rd-cv/qpic)
2. share_label_10w.pkl and train_set_part_boxes.pkl are generated from part-level annotations from [HAKE](https://github.com/DirtyHarryLYL/HAKE-Action-Torch)
3. Test_Faster.pkl is the detected boxes from Faster-RCNN, which is adopted by [TIN](https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network)
