### ISSUE TITLE
Trouble producing the interactiveness AP & HOI mAP reported in the paper.

### ISSUE THREAD

**Issue by Charles-Xie** [enlighten0707/Body-Part-Map-for-Interactiveness#4]
Thanks for your awesome work! 
I try to reproduce the results reported in your paper recently on hico-det dataset, but meet 2 problems:

1. Using the config & training command, I cannot produce the interactiveness AP in 1st training stage.
I follow exactly the steps in your readme, during 100 epochs of training & validation, the interactiveness AP is **37.47** at most. The interactiveness AP reported in the paper is **38.74**. (The training & validation log is here [log.txt](https://github.com/enlighten0707/Body-Part-Map-for-Interactiveness/files/9849809/log.txt).) What could be the reason?

2. The training config & command for 2nd training stage is not provided.
According to your paper, the training consists of 2 stage, first with det & interactiveness loss and second with det & verb loss. The provided training config & command is for the 1st stage (interactiveness cls), and that for the 2nd stage is missing, so the verb cls results and final HOI mAP cannot be reproduced.

I look forward to your reply! Thank you!!! 🙏

**Comment by enlighten0707** [comment]
Hello! We have provided the prediction results of 1-st and 2-nd stage, and auxiliary benchmark code to output final HOI mAP.

**Comment by rohit901** [comment]
I wanted to point out the same issue as you @Charles-Xie 

I think author has provided training config and command only for 1st stage and not for the second stage which is described in the paper. 

I would like to replicate author's results and thus it would be nice if @enlighten0707 can provide training config and instructions for stage 2 training so we can train from scratch and verify.
