### ISSUE TITLE
Where are the verb categories

### ISSUE THREAD

**Issue by hutuo1213** [enlighten0707/Body-Part-Map-for-Interactiveness#9]
Hi, 

You don't seem to have optimized the code you publish, making it a little difficult to read. Can you tell me where the verb classifier for the model is in the code? And how does it work?

**Comment by enlighten0707** [comment]
Hi, 
The provided code makes interactiveness predictions.
In notebooks/eval.ipynb,  the interactiveness predictions are used to apply non-interaction suppression (NIS) on verb classification results.
